### ISSUE TITLE
Crash on a specific circuit input

### ISSUE THREAD

**Issue by ChristopheVuillot** [meamy/t-par#2]
The program crashes on a specific small circuit input, given here:

```
.v 1 2 3
.i 1 2 3

BEGIN

Z 1 2 3
T 1
T 2
T 3

END
```

the crash doesn't happen if the option -synth=GAUSS or -sythn=ADHOC is specified.
I compiled the source with 
- gcc 8.2.1
- boost 1.69.0-1

**Comment by meamy** [comment]
Fixed
