### ISSUE TITLE
.qc file

### ISSUE THREAD

**Issue by monica1131** [meamy/t-par#3]
How to create a .qc file using .qasm file? And how to run the .qc for optimization because I'm not clear with the description provided on the GitHub page.

**Comment by meamy** [comment]
[Feynman](https://github.com/meamy/feynman) supports both .qc and .qasm files and has effectively replaced t-par. T-par is mainly left up for posterity & a few experimental features that never found another home. Unless you have specific need for these features, please use Feynman for circuit optimization instead.
